/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/NvDtdAQYVdF
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Checkbox } from "@/components/ui/checkbox"
import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover"
import { Calendar } from "@/components/ui/calendar"

export function Component() {
  return (
    <div className="w-full max-w-4xl mx-auto p-6 md:p-10">
      <h1 className="text-3xl font-bold mb-6">袋熊系統</h1>
      <div className="space-y-8">
        <div>
          <h2 className="text-xl font-bold mb-4">任務目標設定</h2>
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <label htmlFor="script-style" className="block font-medium">
                腳本風格
              </label>
              <Input placeholder="例如:體育播報記者、童話朗讀說書人" />
            </div>
            <div className="space-y-2">
              <label htmlFor="custom-prompt" className="block font-medium">
                客製化需求
              </label>
              <Textarea placeholder="例如:將新聞內容整理為條列式呈現、情緒高昂、多以感嘆句做結尾" rows={3} />
            </div>
            <div className="space-y-2">
              <label htmlFor="article-limit" className="block font-medium">
                文字上限
              </label>
              <Input id="article-limit" type="number" defaultValue={300} min={100} max={500} />
            </div>
          </div>
        </div>
        <div>
          <h2 className="text-xl font-bold mb-4">設置您的爬蟲</h2>
          <div className="space-y-4">
            <div>
              <label htmlFor="data-sources" className="block font-medium mb-2">
                資料來源
              </label>
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <label htmlFor="website-name" className="block font-medium">
                        網站名稱
                      </label>
                      <Input id="website-name" placeholder="輸入網站名稱" />
                    </div>
                    <div className="space-y-2">
                      <label htmlFor="website-url" className="block font-medium">
                        網站網址
                      </label>
                      <div className="flex items-center gap-2">
                        <Input id="website-url" placeholder="輸入網站網址" />
                        <Button variant="ghost" size="icon">
                          <PlusIcon className="w-4 h-4" />
                          <span className="sr-only">新增</span>
                        </Button>
                      </div>
                    </div>
                    <div className="col-span-2 space-y-2">
                      <label className="block font-medium">已儲存資料來源</label>
                      <div className="grid grid-cols-[1fr_auto] gap-4">
                        <div className="flex items-center gap-2 border rounded-md px-3 py-2">
                          <span>example.com</span>
                          <Button variant="ghost" size="icon">
                            <TrashIcon className="w-4 h-4" />
                            <span className="sr-only">刪除</span>
                          </Button>
                        </div>
                        <div className="flex items-center gap-2 border rounded-md px-3 py-2">
                          <span>news.example.org</span>
                          <Button variant="ghost" size="icon">
                            <TrashIcon className="w-4 h-4" />
                            <span className="sr-only">刪除</span>
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <Button variant="ghost" size="icon">
                    <span className="sr-only">刪除</span>
                  </Button>
                </div>
              </div>
            </div>
            <div>
              <label htmlFor="crawl-frequency" className="block font-medium mb-2">
                資料擷取頻率
              </label>
              <Select id="crawl-frequency">
                <SelectTrigger>
                  <SelectValue placeholder="選擇頻率" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="daily-0">每日 0 時</SelectItem>
                  <SelectItem value="daily-noon">每日中午</SelectItem>
                  <SelectItem value="hourly">每小時</SelectItem>
                  <SelectItem value="weekly">每週</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div>
              <label htmlFor="date-range" className="block font-medium mb-2">
                日期範圍
              </label>
              <div className="flex items-center gap-2">
                <Checkbox id="date-range">
                  <span>擷取過往資料</span>
                </Checkbox>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button variant="outline" className="flex items-center gap-2">
                      <CalendarDaysIcon className="w-4 h-4" />
                      <span>選擇日期區間</span>
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="w-auto p-0" align="start">
                    <Calendar mode="range" />
                  </PopoverContent>
                </Popover>
              </div>
              <p className="text-sm text-muted-foreground">
                針對過往資料進行爬蟲，若選擇此項目，則會在您按下「儲存設定」後，進行「一次性」的腳本生成。若要持續獲取腳本，請回頭取消勾選此設定。
              </p>
            </div>
          </div>
        </div>
        <div>
          <h2 className="text-xl font-bold mb-4">資料篩選設定</h2>
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <label htmlFor="topic-category" className="block font-medium">
                主題類別
              </label>
              <Input placeholder="例如:體育、物理、電影、科技、娛樂" />
            </div>
            <div className="space-y-2">
              <label htmlFor="rare-keywords" className="block font-medium">
                稀有關鍵字
              </label>
              <Input placeholder="輸入逗號分隔的關鍵字，文章資料出現與關鍵字完全相同的字詞時，該文章優先度提升" />
            </div>
            <div className="space-y-2">
              <label htmlFor="filter-keywords" className="block font-medium">
                關鍵字過濾
              </label>
              <Input placeholder="輸入逗號分隔的關鍵字，文章資料出現與關鍵字完全相同的字詞時，該文章不被收錄" />
            </div>
            <div className="space-y-2">
              <label htmlFor="sort-by" className="block font-medium">
                文章優先排序
              </label>
              <Select id="sort-by">
                <SelectTrigger>
                  <SelectValue placeholder="選擇排序方式" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="article-count">文章數</SelectItem>
                  <SelectItem value="keyword-popularity">關鍵字熱門度</SelectItem>
                  <SelectItem value="topic-relevance">與主題關聯性</SelectItem>
                  <SelectItem value="rare-keyword-relevance">與稀有關鍵字關聯性</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </div>
        <div>
          <h2 className="text-xl font-bold mb-4">使用者設定</h2>
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <label htmlFor="user-email" className="block font-medium">
                使用者 Email
              </label>
              <Input id="user-email" type="email" />
            </div>
            <div className="space-y-2">
              <label htmlFor="send-count" className="block font-medium">
                每次寄送腳本數量
                <span className="text-sm text-muted-foreground">
                  依照使用者頻率寄送，擷取資料超過上限時，則依照文章排序設定進行發送
                </span>
              </label>
              <Input id="send-count" type="number" min={1} max={10} />
            </div>
          </div>
        </div>
        <div className="flex justify-end">
          <Button type="submit">儲存設定</Button>
        </div>
      </div>
    </div>
  )
}

function CalendarDaysIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
      <path d="M8 14h.01" />
      <path d="M12 14h.01" />
      <path d="M16 14h.01" />
      <path d="M8 18h.01" />
      <path d="M12 18h.01" />
      <path d="M16 18h.01" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function TrashIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
